services:
  - type: web
    name: medicure-web
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: "/"
    envVars:
      - key: PORT
        value: 10000
